const fs = require('fs');
const file = '/Users/tunahan/net-tapu-platform/apps/web/src/components/block-editor.tsx';
let content = fs.readFileSync(file, 'utf8');

// Find the start of the legal array
const startIdx = content.indexOf('  legal: [');
// Find the start of the withdrawal-rights array
const endIdx = content.indexOf("  'withdrawal-rights': [");

const correctLegal = `  legal: [
    { type: 'hero', title: 'Yasal Bilgiler', subtitle: 'Kullanım koşulları, gizlilik politikası, KVKK aydınlatma metni ve yasal düzenlemeler', gradient: 'from-slate-700 to-slate-900' },
    { type: 'text', content: '<h2>1. Kullanım Koşulları</h2><h3>1.1 Genel Hükümler</h3><p>Bu kullanım koşulları, NetTapu platformunu ("Platform") kullanan tüm kullanıcılar ("Kullanıcı") için geçerlidir. Platforma erişim sağlayarak ve/veya üye olarak bu koşulları kabul etmiş sayılırsınız. Platform, 6098 sayılı Türk Borçlar Kanunu, 6102 sayılı Türk Ticaret Kanunu, 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve ilgili mevzuat çerçevesinde hizmet vermektedir.</p><h3>1.2 Hizmet Tanımı</h3><p>NetTapu, gayrimenkul ve arsa alım-satım işlemlerinin çevrimiçi ortamda gerçekleştirilmesini sağlayan bir açık artırma ve ilan platformudur. Platform; arsa ilan yayınlama, canlı açık artırma, teklif yönetimi, güvenli ödeme altyapısı ve danışmanlık hizmetleri sunmaktadır.</p><h3>1.3 Üyelik Koşulları</h3><p>Platforma üye olmak için 18 yaşını doldurmuş olmak ve T.C. vatandaşı veya Türkiye\\'de yasal ikamet hakkına sahip olmak gerekmektedir. Üyelik sırasında beyan edilen bilgilerin doğruluğundan kullanıcı sorumludur. Yanlış veya yanıltıcı bilgi verilmesi halinde üyelik askıya alınabilir veya iptal edilebilir.</p><h3>1.4 Kullanıcı Yükümlülükleri</h3><p>Kullanıcılar; Platform üzerinden gerçekleştirdikleri tüm işlemlerde ilgili mevzuata uymakla yükümlüdür. Sahte veya yanıltıcı ilan yayınlamak, manipülatif teklif vermek, diğer kullanıcıların haklarını ihlal etmek ve platformun teknik altyapısına zarar vermek kesinlikle yasaktır. Bu kurallara aykırı davranış, üyeliğin derhal sonlandırılması ve yasal işlem başlatılması ile sonuçlanabilir.</p><h3>1.5 Fikri Mülkiyet</h3><p>Platform üzerindeki tüm içerikler, tasarımlar, yazılım kodları, logolar ve markalar NetTapu\\'ya aittir ve 5846 sayılı Fikir ve Sanat Eserleri Kanunu ile korunmaktadır. İzinsiz kopyalama, dağıtma veya ticari amaçla kullanma yasaktır.</p>' },
    { type: 'spacer', size: 'sm' },
    { type: 'text', content: '<h2>2. Gizlilik Politikası</h2><h3>2.1 Toplanan Veriler</h3><p>Platform, hizmet kalitesini artırmak ve yasal yükümlülüklerini yerine getirmek amacıyla aşağıdaki verileri toplamaktadır:</p><ul><li><strong>Kimlik Bilgileri:</strong> Ad, soyad, T.C. kimlik numarası, doğum tarihi</li><li><strong>İletişim Bilgileri:</strong> E-posta adresi, telefon numarası, posta adresi</li><li><strong>Finansal Bilgiler:</strong> Ödeme geçmişi, depozito bilgileri (kredi kartı bilgileri saklanmaz)</li><li><strong>Kullanım Verileri:</strong> IP adresi, tarayıcı bilgisi, sayfa görüntülenme istatistikleri, çerez verileri</li><li><strong>İşlem Verileri:</strong> Teklif geçmişi, ilan etkileşimleri, açık artırma katılım bilgileri</li></ul><h3>2.2 Verilerin Kullanım Amacı</h3><p>Toplanan veriler; hizmet sunumu, kullanıcı deneyiminin iyileştirilmesi, güvenlik önlemlerinin alınması, yasal yükümlülüklerin yerine getirilmesi, pazarlama iletişimleri (onay dahilinde) ve istatistiksel analizler için kullanılmaktadır.</p><h3>2.3 Veri Paylaşımı</h3><p>Kişisel verileriniz, yasal zorunluluklar dışında üçüncü taraflarla paylaşılmaz. Ödeme işlemleri için güvenli POS entegrasyonları (3D Secure) kullanılmakta olup, kredi kartı bilgileri sunucularımızda saklanmamaktadır. Yasal makamlar tarafından talep edilmesi halinde, ilgili mevzuat çerçevesinde veri paylaşımı yapılabilir.</p><h3>2.4 Çerez Politikası</h3><p>Platform, oturum yönetimi, tercih hatırlama ve analitik amaçlarla çerezler kullanmaktadır. Zorunlu çerezler platformun çalışması için gereklidir. Analitik ve pazarlama çerezleri için kullanıcıdan onay alınmaktadır. Çerez tercihlerinizi tarayıcı ayarlarınızdan yönetebilirsiniz.</p>' },
    { type: 'spacer', size: 'sm' },
    { type: 'text', content: '<h2>3. KVKK Aydınlatma Metni</h2><h3>3.1 Veri Sorumlusu</h3><p>6698 sayılı Kişisel Verilerin Korunması Kanunu ("KVKK") kapsamında veri sorumlusu NetTapu Teknoloji A.Ş.\\'dir. Kişisel verileriniz aşağıda açıklanan amaçlar doğrultusunda, hukuka ve dürüstlük kuralına uygun şekilde işlenebilecek, kaydedilebilecek, saklanabilecek, sınıflandırılabilecek, güncellenebilecek ve mevzuatın izin verdiği hallerde üçüncü kişilere aktarılabilecektir.</p><h3>3.2 İşleme Amacı ve Hukuki Sebep</h3><p>Kişisel verileriniz; KVKK\\'nın 5. ve 6. maddelerinde belirtilen hukuki sebeplere dayanarak işlenmektedir. Sözleşmenin kurulması ve ifası, yasal yükümlülüklerin yerine getirilmesi, meşru menfaat ve açık rızanız temel hukuki sebeplerimizdir.</p><h3>3.3 Veri Sahibi Hakları (KVKK Madde 11)</h3><p>KVKK\\'nın 11. maddesi uyarınca her veri sahibi aşağıdaki haklara sahiptir:</p><ul><li>Kişisel verilerin işlenip işlenmediğini öğrenme</li><li>İşlenme amacını ve amaca uygun kullanılıp kullanılmadığını öğrenme</li><li>Yurt içinde veya dışında aktarılıp aktarılmadığını öğrenme</li><li>Eksik veya yanlış işlenmiş ise düzeltilmesini isteme</li><li>İşlenmesini gerektiren sebeplerin ortadan kalkması halinde silinmesini isteme</li><li>İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle aleyhine bir sonucun ortaya çıkması halinde itiraz etme</li><li>Kanuna aykırı işlenmesi sebebiyle zarara uğraması halinde zararın giderilmesini talep etme</li></ul><h3>3.4 Başvuru Yöntemi</h3><p>KVKK kapsamındaki haklarınızı kullanmak için kvkk@nettapu.com adresine yazılı başvuru yapabilirsiniz. Başvurular en geç 30 gün içinde ücretsiz olarak sonuçlandırılacaktır.</p>' },
    { type: 'spacer', size: 'sm' },
    { type: 'text', content: '<h2>4. Elektronik Ticaret Mevzuatı</h2><p>NetTapu, 6563 sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun ve Mesafeli Sözleşmeler Yönetmeliği\\'ne uygun olarak faaliyet göstermektedir. Tüm işlemler öncesinde kullanıcıya ön bilgilendirme yapılmakta, mesafeli satış sözleşmesi sunulmakta ve cayma hakkı tanınan işlemler için yasal süreler içinde iade imkanı sağlanmaktadır.</p><h3>4.1 Ödeme Güvenliği</h3><p>Platform üzerinden yapılan tüm ödemeler, PCI DSS uyumlu ödeme altyapısı ve 3D Secure doğrulama ile gerçekleştirilmektedir. Kredi kartı bilgileri sunucularımızda saklanmamaktadır. Tüm finansal işlemler şifrelenmiş bağlantı üzerinden yürütülmektedir.</p><h3>4.2 Uyuşmazlık Çözümü</h3><p>Bu koşullardan kaynaklanan uyuşmazlıklarda İstanbul Tahkim Merkezi (ISTAC) kuralları uygulanacaktır. Tüketici işlemlerinden kaynaklanan uyuşmazlıklarda tüketici hakem heyetleri ve tüketici mahkemeleri yetkilidir. Uyuşmazlık sınırları her yıl Ticaret Bakanlığı tarafından güncellenmektedir.</p>' },
    { type: 'checklist', heading: 'Yasal Uyum Taahhütlerimiz', items: [
      'KVKK (6698 sayılı Kanun) tam uyumluluk',
      'Elektronik Ticaret Kanunu (6563) çerçevesinde faaliyet',
      'Tüketicinin Korunması Kanunu (6502) uyumu',
      'PCI DSS uyumlu ödeme altyapısı',
      '3D Secure ile güvenli ödeme işlemleri',
      'Kişisel verilerin yurt dışına aktarılmaması',
      'Düzenli bağımsız güvenlik denetimleri',
    ] },
  ],
`;

content = content.substring(0, startIdx) + correctLegal + content.substring(endIdx);
fs.writeFileSync(file, content);
console.log('Fixed block-editor.tsx');
